all: digits fib org strange sum palindrome adder rstrlen

digits: digits.cpp
	g++ -ansi -Wall -o digits digits.cpp

fib: fib.cpp
	g++ -ansi -Wall -o fib fib.cpp

org: org_chart.cpp
	g++ -ansi -Wall -o org org_chart.cpp

strange: strange.cpp
	g++ -ansi -Wall -o strange strange.cpp

sum: sum.cpp
	g++ -ansi -Wall -o sum sum.cpp

palindrome: palindrome.cpp
	g++ -ansi -Wall -o palindrome palindrome.cpp

adder: adder.cpp
	g++ -ansi -Wall -o adder adder.cpp

rstrlen: r_strlen.cpp
	g++ -ansi -Wall -o rstrlen r_strlen.cpp

clean:
	rm -f digits fib org strange sum rstrlen adder palindrome a.out

