all: digits fib org strange sum

digits: digits.cpp
	g++ -ansi -Wall -o digits digits.cpp

fib: fib.cpp
	g++ -ansi -Wall -o fib fib.cpp

org: org_chart.cpp
	g++ -ansi -Wall -o org org_chart.cpp

strange: strange.cpp
	g++ -ansi -Wall -o strange strange.cpp

sum: sum.cpp
	g++ -ansi -Wall -o sum sum.cpp

clean:
	rm -f digits fib org strange sum a.out

